### ISSUE TITLE
关于android-apt插件不能正常安装的问题

### ISSUE THREAD

**Issue by ponyfe** [tianzhijiexian/JsonAnnotation#2]
你好，我在使用这个项目的时候，这个语句会有错，提示无法找到android-apt，现在不是很明白这个是怎么回事。。。请指教一下吧，谢过。

**Comment by kaleai** [comment]
可以把写的代码贴一下，我来看看

**Comment by ponyfe** [comment]
提示：Plugin With id 'android-apt' not found，其中gradle文件如图：![](http://puu.sh/jSCQa/df79935b22.png)

**Comment by kaleai** [comment]
你在project的build.gradle中引入apt的classpath 'com.neenbedankt.gradle.plugins:android-apt:1.7'了吗

**Comment by kaleai** [comment]
这里的classpath 'com.neenbedankt.gradle.plugins:android-apt:1.7'应该在project的build.gradle中引入。所以修改一下就好。

**Comment by ponyfe** [comment]
@tianzhijiexian nice !! 支持一下，这个插件很好啊。。多谢啦

**Comment by kaleai** [comment]
谢谢支持，如果这个问题已经解决了，你可以关闭下问题。谢啦

**Comment by ponyfe** [comment]
closes #2
